import Head from 'next/head'
import { Key } from 'react';
import {PostCard, Categories, PostWidget,Footer} from "../components";
import {getPosts} from "../services";


export default function Home({posts}) {
  return (
    <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>{"Aniketh's Blog"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/download.png" type = "image/x-icon"/>
      </Head>
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
        {posts.map((post, index)=> (
          <PostCard key={index} post={post.node} />
        ))}
        
        </div>
        <div className='lg:col-span-4 col-span-1'>
          <div className='lg:stciky relative top-8'>
            <PostWidget />
            <Categories />
          </div>
        </div>
          <Footer />
          </div>
          
    </div>
  )
}


export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: { posts },
  };
}

